module SignedForm
  module ActionView
    module FormHelper

      # @option options :sign_destination [Boolean] Only the URL given/created will be allowed to receive the form.
      # @option options :digest [Boolean] Digest and verify the views have not been modified
      # @option options :digest_grace_period [Integer] Time in seconds to allow old forms
      # @option options :wrap_form [Symbol] Method of a form builder to wrap. Default is form_for
      def form_for(record, options = {}, &block)
        if options[:signed].nil? && !SignedForm.options[:signed] || !options[:signed].nil? && !options[:signed]
          return super
        end

        options = SignedForm.options.merge options
        options[:builder] ||= ::ActionView::Helpers::FormBuilder

        ancestors = options[:builder].ancestors

        if !ancestors.include?(::ActionView::Helpers::FormBuilder) && !ancestors.include?(SignedForm::FormBuilder)
          raise "Form signing not supported on builders that don't subclass ActionView::Helpers::FormBuilder or include SignedForm::FormBuilder"
        elsif !ancestors.include?(SignedForm::FormBuilder)
          options[:builder] = SignedForm::FormBuilder::BUILDERS[options[:builder]]
        end

        # In Rails < 7, url is written to options and hence available inside SignedForm::FormBuilder
        # In Rails >= 7, url is an ephemeral variable inside `def form_with`, so we need to compute it here.
        # We cannot compute it inside `FormBuilder` as Rails URL helpers (ie. users_path) aren't available in that execution context.
        if options[:sign_destination] && ::ActionView::VERSION::MAJOR >= 7
          # `form_with` passes `options` to `FormBuilder` without `:url` so we need to store the value under a different name.
          # We could also write the url to `options[:url]` to avoid Rails computing it a second time (via `super`) however I decided
          # against that because if the URL generated here differs from the one generated by Rails, a `SignedForm::Errors::InvalidURL`
          # error will be raised on form submit, which is easier to debug than an incorrect `<form action="xxx"` value.
          options[:signed_url] = url_for_form(record, options)
        end

        super record, options do |f|
          output = capture(f, &block)
          f.form_signature_tag + output
        end
      end

      private

      def url_for_form(record, options)
        return options[:url]          if options[:url].is_a?(String)
        return url_for(options[:url]) if options[:url].is_a?(Hash)

        # Url generation extracted from `rails/action_view/lib/action_view/helpers/form_helper.rb#form_with`
        case record
        when String, Symbol
          url_for(options[:url])
        else
          if options[:format].nil?
            polymorphic_path(record, {})
          else
            polymorphic_path(record, format: options[:format])
          end
        end
      end
    end
  end
end

ActionView::Base.send :include, SignedForm::ActionView::FormHelper
